### ISSUE TITLE
Regarding Normalization data

### ISSUE THREAD

**Issue by yogeshverma1998** [google-deepmind/graphcast#11]
Hi,

I have a question regarding the computation of these normalization variables in the demo.ipynb file,

diffs_stddev_by_level = xarray.load_dataset(f).compute()
mean_by_level = xarray.load_dataset(f).compute()
stddev_by_level = xarray.load_dataset(f).compute()

I assume that mean and stddev is global and temporal average mean and std for the grid. Can you let me know how you calculated diffs_stddev_by_level, as I didn't get it from the paper also, I would be grateful if you have the code to compute this in repo. or can you point me to it?

Regards,
Yogesh

**Comment by melmasri** [comment]
Hi @alvarosg, following up on this question, do you have a code that shows this?  It is clear how many time steps do you use to compute the variance, or do you do any spatial averaging across neighboring lat/lng!

How is this normalizations is related to `s_j` in equation (19)?

Thanks in advance.

**Comment by melmasri** [comment]
Hi @alvarosg, just to understand you well. For every lat/lng you compute the variance of the difference over all the dataset, right?

**Comment by alvarosg** [comment]
So for the differences it works like this:

For a given variable (for example geopotential at 500hPa) you take a lat lon map at time $t$ $X^t$ and a lat-lon at time $t+6h$ $X^{t+6h}$, then you compute: the lat-lon map of the differences $D^t=X^{t+6h} -X^t$. $D^t$ gives you 721 * 1440 = 1038240 numbers. 

You repeat this process 8000 times for different values of "t". Each time you get back 1038240 additional numbers.

Once you have all of the 8000 * 1038240 number you compute the mean and the standard deviation of that list of numbers, and those are your normalization statistics for geopotential at 500hPa.

Final notes:
* This explanation was for the difference, but for the actual values you simply do the same directly with $X^t$ rather than with  "$D^t$.
* In practice rather than accumulate all 8000 * 1038240 numbers before computing the mean and stddev, you would use an iterative computation [(for example this)](https://math.stackexchange.com/questions/2148877/iterative-calculation-of-mean-and-standard-deviation).
* Similarly for all of the other variables and pressure level combinations.

**Comment by mjwillson** [comment]
Closing as I believe this answers the question.
